version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: any-comp-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_UiuKag4Tt1kb
      POSTGRES_DB: neondb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
